### ISSUE TITLE
logWhatChangesMe not working

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-debug#40]
This example app: https://github.com/justinbmeyer/my-app

logWhatChangesMe on the `<li>` does not show that the `input` is changing the licensePlate value:

<img width="568" alt="localhost_8080_my-app_" src="https://user-images.githubusercontent.com/78602/37494932-f4136d50-2878-11e8-8cfc-1c4bd820691a.png">

logWhatIChange on the `<input>` shows nothing:

<img width="515" alt="localhost_8080_my-app_" src="https://user-images.githubusercontent.com/78602/37494979-27cb5900-2879-11e8-8103-97a2c49579d6.png">

**Comment by m-mujica** [comment]
@justinbmeyer 

a) About the `li`, We didn't add any mutation tracking to [can-stache-bindings/event](https://github.com/canjs/can-stache-bindings/blob/6d65fc3b4011874cf272b40493c7f86801935419/can-stache-bindings.js#L317-L475) 😨 ... the out you get is due to `can-view-live` binding of `{{licensePlate}}`.

b) about the `input`, I don't think we figured out or event discussed how to do late bindings, debugging your example app, the input binding goes through https://github.com/canjs/can-stache-bindings/blob/6d65fc3b4011874cf272b40493c7f86801935419/can-stache-bindings.js#L520-L523 and there is no mutation tracking in there, see how we only did it for the else block.

**Comment by justinbmeyer** [comment]
This app produces the following graph:

https://gist.github.com/justinbmeyer/1ca0010c8747fff52260d363c6b164b8#gistcomment-2382991


![image](https://user-images.githubusercontent.com/78602/37608392-6d9b33b4-2b68-11e8-922b-15066894f2a0.png)


What are the two `Observation<>` at the bottom for?

**Comment by phillipskevin** [comment]
In the first example, `logWhatIChange` on the `<input>` works if you pass `"value"` for the key:

![image](https://user-images.githubusercontent.com/5851984/37681401-970f4bf8-2c54-11e8-815e-0c5ab2988019.png)

**Comment by justinbmeyer** [comment]
It also seems like `logWhatIChange` is failing with:

```js
Component.extend({
    tag: "my-app",
    view: `
        <h1>{{message}} World!</h1>
        <input value:bind='message'/>
    `,
    ViewModel: {
        message: {default: "Hello"}
    }
});
```

on the `<input/>`

**Comment by phillipskevin** [comment]
The issues with 
```
        <h1>{{message}} World!</h1>
        <input value:bind='message'/>
```
have been fixed.

The graph for the `<h1>`:
![image](https://user-images.githubusercontent.com/5851984/37804717-a6f4c2ae-2e03-11e8-84ba-e74ebdb73e4d.png)

and for the `<input>`:
![image](https://user-images.githubusercontent.com/5851984/37804724-b565ac36-2e03-11e8-9b8a-e535c83cf5e0.png)

I still want to look into why those `Observation`s are in the graph, so I'll leave this open for now.

I also need to re-check https://github.com/justinbmeyer/my-app.

**Comment by phillipskevin** [comment]
I think all these issues are resolve now. Here is the `logWhatChangesMe` for the `<li>` in the "my-app" example showing that the `<input>` is changing the `licensePlate` value:

![image](https://user-images.githubusercontent.com/5851984/38199821-b92464b4-3657-11e8-9009-784ade3d3bc4.png)
